import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Recarga el inventario de activos fijos de San Bartolomé desde la transcripción
 * completa de la planilla del traspaso, y reemplaza la carga anterior.
 *
 * La primera carga (`SeedSanBartolomeAssets`) salió de una transcripción parcial:
 * 207 filas y 500 unidades, sin el estado real de cada bien. Esta trae **244
 * filas y 729 unidades entregadas**, y tres datos que antes no existían:
 *
 * - **El estado real**. La planilla marca con "N" lo que no funciona: un cable de
 *   estabilizador y la balanza pediátrica entran como `damaged`/`poor`, y no como
 *   "bueno" y "activo" igual que todo lo demás, que era una suposición.
 * - **Lo que figura en planilla pero nadie firmó como entregado** (41 filas → 49
 *   fichas): los sillones de la sala de espera, las mesas del cuarto, la garrafa.
 *   Entran como `inactive` con la nota, para confirmarlos en el primer conteo
 *   físico en vez de desaparecer del sistema.
 * - **Las 57 dudas de transcripción** ("Confirmar 42 vs 43", "Cantidad en pz vs
 *   caja"), que quedan en las notas de las 68 fichas afectadas y ahora se pueden
 *   resolver desde la ficha, no contra el papel.
 *
 * **Las 9 filas NO_ENTREGADO no se cargan** (agua oxigenada, povidona, detergente,
 * espéculos): la planilla las lista con 0 unidades. Listarlas haría que el acta de
 * entrega afirme que se recibió algo que nunca llegó.
 *
 * Se mantiene el criterio de la carga anterior: **hasta 5 unidades, una ficha por
 * unidad** —dos ecógrafos se siguen por separado y uno se puede dar de baja sin
 * tocar el otro—; por encima de 5, una sola ficha con la cantidad en las notas,
 * porque 72 bránulas no son activos que se sigan uno a uno. Quedan **334 fichas**.
 *
 * Sigue **sin fecha ni precio de compra**: la planilla no los trae. Ver
 * `MakeAssetPurchaseDateOptional` — una fecha inventada haría que en cinco años el
 * sistema afirme que un ecógrafo de segunda mano tiene exactamente cinco años.
 *
 * **Borra las fichas `AF-%` anteriores y renumera desde AF-0001.** Es seguro
 * porque ninguna de las 290 fue editada desde su carga y no hay mantenimientos ni
 * traslados que las referencien; se verificó en producción antes de escribir esto.
 * Si aparecieran, el DELETE fallaría por la FK en vez de dejar filas colgando.
 */
export class ReloadSanBartolomeAssets1786360000000 implements MigrationInterface {
  name = 'ReloadSanBartolomeAssets1786360000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM "assets" WHERE "assetTag" LIKE 'AF-%'`);

    // Los importes van explícitos porque un INSERT de migración no dispara el
    // hook `@BeforeInsert` que normalmente los calcula, y son NOT NULL.
    await queryRunner.query(`
      INSERT INTO "assets"
        ("assetTag", "name", "type", "status", "condition", "purchasePrice", "purchaseDate",
         "depreciationMethod", "usefulLifeYears", "salvageValue", "currentValue",
         "accumulatedDepreciation", "monthlyDepreciation", "maintenanceIntervalMonths",
         "totalMaintenanceCost", "location", "notes", "isActive", "clinic_id")
      SELECT v.tag, v.nombre, v.tipo::"assets_type_enum", v.estado::"assets_status_enum",
             v.condicion::"assets_condition_enum", 0, NULL,
             'no_depreciation', 0, 0, 0, 0, 0, 0, 0, v.ambiente, v.notas, true, c."id"
      FROM (VALUES
        ('AF-0001', 'Ecógrafo marca CHAIZON color blanco', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'En planilla figura 1+1 (equipo + cable); se desglosa'),
        ('AF-0002', 'Cable negro de ecógrafo CHAIZON', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'Desglosado del 1+1 del ítem 1'),
        ('AF-0003', 'Escritorio porta ecógrafo color café de tres peldaños', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0004', 'Transductor intravaginal', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0005', 'Transductor convexo', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0006', 'Cables de transductores (1 de 2)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0007', 'Cables de transductores (2 de 2)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0008', 'Estabilizador de electricidad', 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0009', 'Cable negro de estabilizador (1 de 2)', 'computer', 'damaged', 'poor', 'SALA ECOGRAFIA', 'Marcado con N en la planilla (no funciona) REVISAR: Confirmar a qué fila corresponde la N.'),
        ('AF-0010', 'Cable negro de estabilizador (2 de 2)', 'computer', 'damaged', 'poor', 'SALA ECOGRAFIA', 'Marcado con N en la planilla (no funciona) REVISAR: Confirmar a qué fila corresponde la N.'),
        ('AF-0011', 'Impresora color blanco', 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0012', 'Electrocardiógrafo marca ZONCARE color blanco', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'La planilla no tiene ítem 9'),
        ('AF-0013', 'Cable de electrocardiógrafo', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0014', 'Cable para sensores', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0015', 'Sensores pectorales de colores adulto', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', '6 unidades en una sola ficha.'),
        ('AF-0016', 'Sensores de miembros de colores adulto (1 de 4)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0017', 'Sensores de miembros de colores adulto (2 de 4)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0018', 'Sensores de miembros de colores adulto (3 de 4)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0019', 'Sensores de miembros de colores adulto (4 de 4)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0020', 'Sensores pectorales color azul pediátricos', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', '6 unidades en una sola ficha.'),
        ('AF-0021', 'Sensores de miembros color azul pediátricos (1 de 4)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0022', 'Sensores de miembros color azul pediátricos (2 de 4)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0023', 'Sensores de miembros color azul pediátricos (3 de 4)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0024', 'Sensores de miembros color azul pediátricos (4 de 4)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0025', 'Doppler fetal color rosado', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0026', 'Monitor marca LG', 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0027', 'Monitor marca MASTER G', 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0028', 'Escritorio color café', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0029', 'Silla color naranja', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0030', 'Gradilla', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0031', 'Camilla ginecológica color café oscuro', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0032', 'Pierneras de camilla ginecológica (1 de 2)', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0033', 'Pierneras de camilla ginecológica (2 de 2)', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0034', 'Camilla de revisión', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0035', 'Lámparas cuello de ganso (1 de 2)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0036', 'Lámparas cuello de ganso (2 de 2)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0037', 'Taburetes giratorios color café oscuro (1 de 2)', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0038', 'Taburetes giratorios color café oscuro (2 de 2)', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0039', 'Biombos color blanco (1 de 2)', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0040', 'Biombos color blanco (2 de 2)', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0041', 'Porta suero', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0042', 'Mesa de mayo', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0043', 'Tambor de acero mediano', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0044', 'Ligadura color celeste', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0045', 'Balanza pediátrica color blanco', 'medical_equipment', 'damaged', 'poor', 'SALA ECOGRAFIA', 'Marcada con N en la planilla (no funciona) REVISAR: Confirmar a qué fila corresponde la N.'),
        ('AF-0046', 'Bidón de agua celeste (1 de 2)', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0047', 'Bidón de agua celeste (2 de 2)', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0048', 'Botella porta gel grande (1 de 2)', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0049', 'Botella porta gel grande (2 de 2)', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0050', 'Porta colposcopio de acero con dos brazos', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'La planilla no tiene ítem 36'),
        ('AF-0051', 'Cámara de colposcopio con tapa marca EDDAN', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0052', 'Cable de cámara', 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0053', 'Laptop marca TOSHIBA', 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0054', 'Cable de laptop color negro', 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0055', 'Cables de colposcopio color negro', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0056', 'Porta pico (1 de 4)', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0057', 'Porta pico (2 de 4)', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0058', 'Porta pico (3 de 4)', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0059', 'Porta pico (4 de 4)', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0060', 'Tela grande color celeste (1 de 2)', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0061', 'Tela grande color celeste (2 de 2)', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0062', 'Tela grande color rosado', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0063', 'Tela para biombo color blanco', 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0064', 'Cauterizador (1 de 2)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0065', 'Cauterizador (2 de 2)', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0066', 'Agujas de cauterizador', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', '42 unidades en una sola ficha. Falta 1 respecto a planilla Planilla 43, entregado 42. REVISAR: Confirmar 42 vs 43.'),
        ('AF-0067', 'Regla de 60 cm', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0068', 'Negatoscopio', 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0069', 'Caja de guantes', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Unidad: caja.'),
        ('AF-0070', 'Vaselina líquida', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Unidad: frasco.'),
        ('AF-0071', 'Otoscopio color blanco', 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'Fila sin numero en planilla'),
        ('AF-0072', 'Cubridores (1 de 4)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Fila sin numero en planilla'),
        ('AF-0073', 'Cubridores (2 de 4)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Fila sin numero en planilla'),
        ('AF-0074', 'Cubridores (3 de 4)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Fila sin numero en planilla'),
        ('AF-0075', 'Cubridores (4 de 4)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Fila sin numero en planilla'),
        ('AF-0076', 'Porta cubridor', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Fila sin numero en planilla'),
        ('AF-0077', 'Papel de electrocardiógrafo (1 de 5)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano Unidad: rollo.'),
        ('AF-0078', 'Papel de electrocardiógrafo (2 de 5)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano Unidad: rollo.'),
        ('AF-0079', 'Papel de electrocardiógrafo (3 de 5)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano Unidad: rollo.'),
        ('AF-0080', 'Papel de electrocardiógrafo (4 de 5)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano Unidad: rollo.'),
        ('AF-0081', 'Papel de electrocardiógrafo (5 de 5)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano Unidad: rollo.'),
        ('AF-0082', 'Taza de porcelana (1 de 3)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano'),
        ('AF-0083', 'Taza de porcelana (2 de 3)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano'),
        ('AF-0084', 'Taza de porcelana (3 de 3)', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano'),
        ('AF-0085', 'Botella de alcohol en gel', 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano Unidad: botella.'),
        ('AF-0086', 'Tabletas de carbón', 'other', 'active', 'good', 'SALA ECOGRAFIA', '10 unidades en una sola ficha. Agregado a mano; cantidad corregida a 10 Unidad: tableta.'),
        ('AF-0087', 'Estante de fierro color café', 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0088', 'Biombo blanco', 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0089', 'Mesa de mayo color blanco, completa', 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0090', 'Camilla de revisión color café', 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0091', 'Silla de toma de presión color café', 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0092', 'Extintor rojo', 'other', 'active', 'good', 'SALA ENFERMERIA', 'La planilla no tiene ítem 6'),
        ('AF-0093', 'Tambores de acero inoxidable (1 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0094', 'Tambores de acero inoxidable (2 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0095', 'Tambores de acero inoxidable (3 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0096', 'Tambores de acero inoxidable (4 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0097', 'Botiquín de primeros auxilios', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0098', 'Charola de aluminio', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0099', 'Estetoscopio (1 de 3)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', 'Falta 1 respecto a planilla Planilla 4, entregado 3. REVISAR: Confirmar 3 vs 4.'),
        ('AF-0100', 'Estetoscopio (2 de 3)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', 'Falta 1 respecto a planilla Planilla 4, entregado 3. REVISAR: Confirmar 3 vs 4.'),
        ('AF-0101', 'Estetoscopio (3 de 3)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', 'Falta 1 respecto a planilla Planilla 4, entregado 3. REVISAR: Confirmar 3 vs 4.'),
        ('AF-0102', 'Tensiómetro (2 manuales y 2 digitales) (1 de 4)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0103', 'Tensiómetro (2 manuales y 2 digitales) (2 de 4)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0104', 'Tensiómetro (2 manuales y 2 digitales) (3 de 4)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0105', 'Tensiómetro (2 manuales y 2 digitales) (4 de 4)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0106', 'Vitrinas de aluminio color café plomo (1 de 2)', 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0107', 'Vitrinas de aluminio color café plomo (2 de 2)', 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0108', 'Monitor de cámaras', 'computer', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0109', 'Monitor de cámara grande', 'computer', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0110', 'Bránulas de todo calibre', 'other', 'active', 'good', 'SALA ENFERMERIA', '72 unidades en una sola ficha. Diferencia importante frente a planilla Planilla 106, entregado 72.'),
        ('AF-0111', 'Equipo para enemas', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0112', 'Guantes estériles', 'other', 'active', 'good', 'SALA ENFERMERIA', '14 unidades en una sola ficha. Unidad: par. Planilla 19, entregado 14.'),
        ('AF-0113', 'Nebulizador celeste pequeño', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0114', 'Mascarillas (1 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Cantidad corregida a mano en planilla'),
        ('AF-0115', 'Mascarillas (2 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Cantidad corregida a mano en planilla'),
        ('AF-0116', 'Mascarillas (3 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Cantidad corregida a mano en planilla'),
        ('AF-0117', 'Mascarillas (4 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Cantidad corregida a mano en planilla'),
        ('AF-0118', 'Caja abierta de jeringas 3 ml', 'other', 'active', 'good', 'SALA ENFERMERIA', '12 unidades en una sola ficha. Entregado contado en piezas sueltas Planilla 1, entregado 12. REVISAR: Cantidad en pz vs caja.'),
        ('AF-0119', 'Caja abierta de agujas 21G 1 1/2', 'other', 'active', 'good', 'SALA ENFERMERIA', '8 unidades en una sola ficha. Entregado contado en piezas sueltas Planilla 2, entregado 8. REVISAR: Cantidad en pz vs caja.'),
        ('AF-0120', 'Caja abierta de agujas 27G 1 1/2', 'other', 'active', 'good', 'SALA ENFERMERIA', '137 unidades en una sola ficha. Entregado contado en piezas sueltas Planilla 2, entregado 137. REVISAR: Cantidad en pz vs caja.'),
        ('AF-0121', 'Oxímetro (1 de 2)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', 'Entregado mayor a planilla Planilla 1, entregado 2. REVISAR: Confirmar 2 vs 1.'),
        ('AF-0122', 'Oxímetro (2 de 2)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', 'Entregado mayor a planilla Planilla 1, entregado 2. REVISAR: Confirmar 2 vs 1.'),
        ('AF-0123', 'Micropore', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Diferencia frente a planilla Unidad: rollo. Planilla 7, entregado 1. REVISAR: Confirmar 1 vs 7.'),
        ('AF-0124', 'Nebulizador grande celeste', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0125', 'Balde de guantes abiertos (1 de 2)', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0126', 'Balde de guantes abiertos (2 de 2)', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0127', 'Vendas elásticas 20 cm (1 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0128', 'Vendas elásticas 20 cm (2 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0129', 'Vendas elásticas 20 cm (3 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0130', 'Vendas elásticas 20 cm (4 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0131', 'Sondas vesicales (1 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Planilla 5, entregado 4.'),
        ('AF-0132', 'Sondas vesicales (2 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Planilla 5, entregado 4.'),
        ('AF-0133', 'Sondas vesicales (3 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Planilla 5, entregado 4.'),
        ('AF-0134', 'Sondas vesicales (4 de 4)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Planilla 5, entregado 4.'),
        ('AF-0135', 'Termómetro de mercurio (1 de 2)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0136', 'Termómetro de mercurio (2 de 2)', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0137', 'Cinta métrica', 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0138', 'Balanza con tallímetro', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0139', 'Taburete verde', 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0140', 'Hilos', 'other', 'active', 'good', 'SALA ENFERMERIA', '6 unidades en una sola ficha. Agregado a mano'),
        ('AF-0141', 'Balón de oxígeno grande', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0142', 'Porta suero', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0143', 'Gradilla', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0144', 'Caja abierta de jeringas 20 ml', 'other', 'active', 'good', 'SALA ENFERMERIA', '18 unidades en una sola ficha. Agregado a mano'),
        ('AF-0145', 'Caja abierta de jeringas 50 ml', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0146', 'Lidocaína (1 de 5)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano Unidad: frasco.'),
        ('AF-0147', 'Lidocaína (2 de 5)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano Unidad: frasco.'),
        ('AF-0148', 'Lidocaína (3 de 5)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano Unidad: frasco.'),
        ('AF-0149', 'Lidocaína (4 de 5)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano Unidad: frasco.'),
        ('AF-0150', 'Lidocaína (5 de 5)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano Unidad: frasco.'),
        ('AF-0151', 'Matabicharaco color azul', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano REVISAR: Confirmar nombre del producto.'),
        ('AF-0152', 'Ácido acético', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano Unidad: frasco.'),
        ('AF-0153', 'Basureros (1 de 3)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0154', 'Basureros (2 de 3)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0155', 'Basureros (3 de 3)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0156', 'Mortero', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie de la planilla'),
        ('AF-0157', 'Agujas de sutura', 'other', 'active', 'good', 'SALA ENFERMERIA', '6 unidades en una sola ficha. Anexo manuscrito al pie REVISAR: Confirmar descripcion.'),
        ('AF-0158', 'Frascos de vidrio (1 de 3)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0159', 'Frascos de vidrio (2 de 3)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0160', 'Frascos de vidrio (3 de 3)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0161', 'Bisturí', 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', '7 unidades en una sola ficha. Anexo manuscrito al pie'),
        ('AF-0162', 'Tapón (1 de 3)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0163', 'Tapón (2 de 3)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0164', 'Tapón (3 de 3)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0165', 'Vendas de yeso (1 de 2)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0166', 'Vendas de yeso (2 de 2)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0167', 'Solución glucosada (1 de 2)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie Unidad: frasco.'),
        ('AF-0168', 'Solución glucosada (2 de 2)', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie Unidad: frasco.'),
        ('AF-0169', 'Riñonera plastica amarilla', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0170', 'Atomizador rosado', 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0171', 'Frascos de vidrio (segundo lote)', 'other', 'active', 'good', 'SALA ENFERMERIA', '7 unidades en una sola ficha. Anexo manuscrito al pie'),
        ('AF-0172', 'Equipo de wifi', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0173', 'Frasco de vidrio con oxímetro verde (1 de 2)', 'medical_equipment', 'inactive', 'good', 'CONSULTORIO MEDICO 1', 'En planilla figura 1+1; sin dato en Entregado Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0174', 'Frasco de vidrio con oxímetro verde (2 de 2)', 'medical_equipment', 'inactive', 'good', 'CONSULTORIO MEDICO 1', 'En planilla figura 1+1; sin dato en Entregado Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0175', 'Termómetro digital', 'medical_equipment', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0176', 'Control', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', 'REVISAR: Precisar de qué equipo es el control.'),
        ('AF-0177', 'Engrampadora (1 de 2)', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0178', 'Engrampadora (2 de 2)', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0179', 'Perforadora', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0180', 'Candados grandes (1 de 4)', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0181', 'Candados grandes (2 de 4)', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0182', 'Candados grandes (3 de 4)', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0183', 'Candados grandes (4 de 4)', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0184', 'Candados pequeños (1 de 2)', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0185', 'Candados pequeños (2 de 2)', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0186', 'Aspiradoras (1 de 2)', 'medical_equipment', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0187', 'Aspiradoras (2 de 2)', 'medical_equipment', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0188', 'Máscara grande color celeste', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0189', 'Máscara transparente', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0190', 'Lentes transparentes', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0191', 'Tóner', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0192', 'Cable plomo', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0193', 'Escritorio color café de dos piezas', 'furniture', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0194', 'Impresora EPSON (1 de 2)', 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0195', 'Impresora EPSON (2 de 2)', 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0196', 'Cable blanco y negro', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0197', 'Monitor (1 de 2)', 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0198', 'Monitor (2 de 2)', 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0199', 'Cable negro de monitor', 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0200', 'Teclado', 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0201', 'Cable para teclado negro', 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0202', 'Ratón con cable', 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0203', 'Porta pico (1 de 2)', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', 'En planilla figura 1+1; numeración 21 repetida'),
        ('AF-0204', 'Porta pico (2 de 2)', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', 'En planilla figura 1+1; numeración 21 repetida'),
        ('AF-0205', 'Basurero color negro', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Numeración 22 repetida en planilla'),
        ('AF-0206', 'Caldera eléctrica', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0207', 'Grampas, caja abierta', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Unidad: caja.'),
        ('AF-0208', 'Gestograma', 'other', 'inactive', 'good', 'CONSULTORIO MEDICO 1', 'Entregado marcado con guion Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Confirmar si no fue entregado.'),
        ('AF-0209', 'Yurex', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0210', 'Porta lápiz de madera', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0211', 'Sillas cafés', 'furniture', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0212', 'Sillón blanco con café (1 de 2)', 'furniture', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0213', 'Sillón blanco con café (2 de 2)', 'furniture', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0214', 'Florero con flores', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0215', 'Cámara', 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Agregado a mano'),
        ('AF-0216', 'Flash', 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Agregado a mano'),
        ('AF-0217', 'Glucómetro', 'medical_equipment', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Agregado a mano'),
        ('AF-0218', 'Recetarios', 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', '25 unidades en una sola ficha. Agregado a mano'),
        ('AF-0219', 'Basurero color negro', 'other', 'active', 'good', 'BAÑO', NULL),
        ('AF-0220', 'Jarra pequeña color café', 'other', 'active', 'good', 'BAÑO', NULL),
        ('AF-0221', 'Limpiador de baño rosado', 'other', 'active', 'good', 'BAÑO', 'Agregado a mano'),
        ('AF-0222', 'Escobas (1 de 2)', 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0223', 'Escobas (2 de 2)', 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0224', 'Goma', 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0225', 'Basurero', 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0226', 'Toalla', 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0227', 'Sillón pequeño', 'furniture', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0228', 'Lavandina', 'other', 'active', 'good', 'LAVANDERIA', 'Unidad: botella. Planilla 3, entregado 1.'),
        ('AF-0229', 'Limpia piso', 'other', 'active', 'good', 'LAVANDERIA', 'Unidad: botella. Planilla 3, entregado 1.'),
        ('AF-0230', 'Virutilla', 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0231', 'Esponja', 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0232', 'Cepillos (1 de 2)', 'other', 'active', 'good', 'LAVANDERIA', 'Agregado a mano'),
        ('AF-0233', 'Cepillos (2 de 2)', 'other', 'active', 'good', 'LAVANDERIA', 'Agregado a mano'),
        ('AF-0234', 'Balde', 'other', 'active', 'good', 'LAVANDERIA', 'Agregado a mano'),
        ('AF-0235', 'Pupinel color blanco', 'medical_equipment', 'active', 'good', 'ESTERILIZACION', 'En planilla figura 1+1 (equipo + cable); se desglosa'),
        ('AF-0236', 'Cable de pupinel', 'medical_equipment', 'active', 'good', 'ESTERILIZACION', 'Desglosado del 1+1 del ítem 1'),
        ('AF-0237', 'Centrifugadora', 'medical_equipment', 'active', 'good', 'ESTERILIZACION', 'En planilla figura 1+1 (equipo + cable); se desglosa'),
        ('AF-0238', 'Cable de centrifugadora', 'medical_equipment', 'active', 'good', 'ESTERILIZACION', 'Desglosado del 1+1 del ítem 2'),
        ('AF-0239', 'Mesa de mayo de dos cuerpos con bandeja pequeña', 'furniture', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0240', 'Cable blanco', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0241', 'Basurero naranja', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0242', 'Riñonera de plástico amarillo', 'other', 'inactive', 'good', 'ESTERILIZACION', 'Entregado marcado con guion Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Confirmar si no fue entregado.'),
        ('AF-0243', 'Caja de equipo grande de metal con tapa', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0244', 'Riñoneras (1 de 3)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0245', 'Riñoneras (2 de 3)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0246', 'Riñoneras (3 de 3)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0247', 'Riñonera redonda', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0248', 'Caja de curación con tapa', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0249', 'Espéculo S', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0250', 'Pinza diente de ratón (1 de 2)', 'medical_equipment', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0251', 'Pinza diente de ratón (2 de 2)', 'medical_equipment', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0252', 'Pinza anatómica (1 de 2)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0253', 'Pinza anatómica (2 de 2)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0254', 'Tijera mayo (1 de 2)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0255', 'Tijera mayo (2 de 2)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0256', 'Pinza Kelly (1 de 3)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0257', 'Pinza Kelly (2 de 3)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0258', 'Pinza Kelly (3 de 3)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0259', 'Porta aguja', 'other', 'active', 'good', 'ESTERILIZACION', '6 unidades en una sola ficha.'),
        ('AF-0260', 'Mango de bisturí (1 de 3)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0261', 'Mango de bisturí (2 de 3)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0262', 'Mango de bisturí (3 de 3)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0263', 'Pinza punta fina', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0264', 'Pinza para campos', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0265', 'Pinza aro', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0266', 'Cureta pequeña larga', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0267', 'Cureta ancha (1 de 2)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0268', 'Cureta ancha (2 de 2)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0269', 'Corta uña', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0270', 'Equipo de retiro de uñero', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0271', 'Tubos celestes Chulumani', 'other', 'active', 'good', 'ESTERILIZACION', '8 unidades en una sola ficha. Planilla 10, entregado 8.'),
        ('AF-0272', 'Tubos celestes Irupana', 'other', 'active', 'good', 'ESTERILIZACION', '45 unidades en una sola ficha. Entregado mayor a planilla Planilla 34, entregado 45. REVISAR: Confirmar 45 vs 34.'),
        ('AF-0273', 'Tubos rojos (1 de 5)', 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 6, entregado 5.'),
        ('AF-0274', 'Tubos rojos (2 de 5)', 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 6, entregado 5.'),
        ('AF-0275', 'Tubos rojos (3 de 5)', 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 6, entregado 5.'),
        ('AF-0276', 'Tubos rojos (4 de 5)', 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 6, entregado 5.'),
        ('AF-0277', 'Tubos rojos (5 de 5)', 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 6, entregado 5.'),
        ('AF-0278', 'Tubos morados', 'other', 'active', 'good', 'ESTERILIZACION', '7 unidades en una sola ficha. Planilla 8, entregado 7.'),
        ('AF-0279', 'Tubos amarillos', 'other', 'active', 'good', 'ESTERILIZACION', '8 unidades en una sola ficha. Planilla 10, entregado 8.'),
        ('AF-0280', 'Prueba de embarazo', 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 4, entregado 1.'),
        ('AF-0281', 'Tubos Eppendorf (1 de 2)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0282', 'Tubos Eppendorf (2 de 2)', 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0283', 'Toalla roja', 'other', 'active', 'good', 'ESTERILIZACION', '15 unidades en una sola ficha. Planilla 1, entregado 15. REVISAR: Cifra dudosa: revisar 15 vs 1.'),
        ('AF-0284', 'Tubo Sandra', 'other', 'active', 'good', 'ESTERILIZACION', 'Agregado a mano REVISAR: Confirmar descripcion.'),
        ('AF-0285', 'Paquete de bolsas negras, abierto (1 de 4)', 'other', 'active', 'good', 'ESTERILIZACION', 'Agregado a mano Unidad: paquete.'),
        ('AF-0286', 'Paquete de bolsas negras, abierto (2 de 4)', 'other', 'active', 'good', 'ESTERILIZACION', 'Agregado a mano Unidad: paquete.'),
        ('AF-0287', 'Paquete de bolsas negras, abierto (3 de 4)', 'other', 'active', 'good', 'ESTERILIZACION', 'Agregado a mano Unidad: paquete.'),
        ('AF-0288', 'Paquete de bolsas negras, abierto (4 de 4)', 'other', 'active', 'good', 'ESTERILIZACION', 'Agregado a mano Unidad: paquete.'),
        ('AF-0289', 'Esponja', 'other', 'active', 'good', 'ESTERILIZACION', 'Agregado a mano'),
        ('AF-0290', 'Sillones (1 de 5)', 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0291', 'Sillones (2 de 5)', 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0292', 'Sillones (3 de 5)', 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0293', 'Sillones (4 de 5)', 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0294', 'Sillones (5 de 5)', 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0295', 'Mesa', 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0296', 'Timbre', 'other', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0297', 'Cámara', 'computer', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0298', 'Sillones de madera (1 de 2)', 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0299', 'Sillones de madera (2 de 2)', 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0300', 'Manguera azul', 'other', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0301', 'Garrafa', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0302', 'Mesa amarilla', 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0303', 'Mesa verde', 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0304', 'Manguera de garrafa', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0305', 'Catre de una plaza', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0306', 'Payasa (colchoneta)', 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0307', 'Frazada guinda', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0308', 'Frazada ploma con banderita', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0309', 'Cubrecama amarilla', 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0310', 'Almohada con protector', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0311', 'Sillón', 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0312', 'Silla', 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0313', 'Platos planos de plástico (1 de 2)', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0314', 'Platos planos de plástico (2 de 2)', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0315', 'Plato hondo de porcelana azul', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0316', 'Plato hondo de plástico', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0317', 'Termo pequeño', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0318', 'Azucarera de porcelana', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0319', 'Tazas de porcelana (1 de 2)', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0320', 'Tazas de porcelana (2 de 2)', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0321', 'Copa de vidrio', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0322', 'Copa de plástico', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0323', 'Canasta pequeña verde', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0324', 'Cucharón', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0325', 'Espumadera de metal', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0326', 'Cuchara de metal', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0327', 'Tenedor', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0328', 'Cuchillo de mesa', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0329', 'Cuchillo grande rojo', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0330', 'Raspador plano', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0331', 'Exprimidor plano', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0332', 'Olla mediana', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0333', 'Sartén grande', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0334', 'Jarra pequeña', 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.')
      ) AS v(tag, nombre, tipo, estado, condicion, ambiente, notas)
      CROSS JOIN (SELECT "id" FROM "clinics" WHERE "name" ILIKE 'San Bartolom%' LIMIT 1) c
      ON CONFLICT ("assetTag") DO NOTHING
    `);
  }

  /**
   * Vuelve al estado anterior a esta migración: sin las fichas nuevas. No
   * restituye las 290 de la carga anterior — para eso hay que revertir también
   * `SeedSanBartolomeAssets` y volver a aplicarla.
   */
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM "assets" WHERE "assetTag" LIKE 'AF-%'`);
  }
}
