import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Recarga el inventario de San Bartolomé como conteo de existencias: **una fila
 * por ítem con su cantidad**, en vez de una ficha por unidad.
 *
 * Las dos cargas anteriores partían de tratar cada bien como un activo contable
 * individual, y sin un campo de cantidad la misma planilla entraba con dos
 * criterios opuestos: la caja de 137 agujas quedaba como una ficha con el número
 * escondido en una nota, mientras 4 sensores se abrían en cuatro fichas
 * "(1 de 4)". Con `quantity` (ver `AddAssetQuantity`) el inventario responde lo
 * que la clínica pregunta —qué hay, cuánto y dónde— y las 334 fichas se colapsan
 * en **235 ítems / 778 unidades**, que es exactamente lo que dice el papel.
 *
 * Se conserva todo lo ganado en la carga anterior: el estado real de la planilla
 * (2 ítems marcados como no operativos), los 41 que figuran sin entrega firmada
 * —entran como `inactive` para confirmarlos en el conteo físico— y las dudas de
 * transcripción en las notas de los 56 ítems afectados. Las 9 filas no entregadas
 * siguen fuera: listarlas haría que el acta afirme que se recibió algo que nunca
 * llegó.
 *
 * Sin fecha ni precio de compra, como antes: la planilla no los trae, y el
 * inventario no se lleva para contabilidad sino para saber qué hay en cada
 * ambiente.
 *
 * Borra las fichas `AF-%` y renumera desde AF-0001. Seguro porque ninguna fue
 * editada y no hay mantenimientos ni traslados que las referencien.
 */
export class ReloadSanBartolomeAssetsWithQuantity1786380000000 implements MigrationInterface {
  name = 'ReloadSanBartolomeAssetsWithQuantity1786380000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM "assets" WHERE "assetTag" LIKE 'AF-%'`);

    // Los importes van explícitos porque un INSERT de migración no dispara el
    // hook `@BeforeInsert` que normalmente los calcula, y son NOT NULL.
    await queryRunner.query(`
      INSERT INTO "assets"
        ("assetTag", "name", "quantity", "type", "status", "condition", "purchasePrice", "purchaseDate",
         "depreciationMethod", "usefulLifeYears", "salvageValue", "currentValue",
         "accumulatedDepreciation", "monthlyDepreciation", "maintenanceIntervalMonths",
         "totalMaintenanceCost", "location", "notes", "isActive", "clinic_id")
      SELECT v.tag, v.nombre, v.cantidad, v.tipo::"assets_type_enum", v.estado::"assets_status_enum",
             v.condicion::"assets_condition_enum", 0, NULL,
             'no_depreciation', 0, 0, 0, 0, 0, 0, 0, v.ambiente, v.notas, true, c."id"
      FROM (VALUES
        ('AF-0001', 'Ecógrafo marca CHAIZON color blanco', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'En planilla figura 1+1 (equipo + cable); se desglosa'),
        ('AF-0002', 'Cable negro de ecógrafo CHAIZON', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'Desglosado del 1+1 del ítem 1'),
        ('AF-0003', 'Escritorio porta ecógrafo color café de tres peldaños', 1, 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0004', 'Transductor intravaginal', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0005', 'Transductor convexo', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0006', 'Cables de transductores', 2, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0007', 'Estabilizador de electricidad', 1, 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0008', 'Cable negro de estabilizador', 2, 'computer', 'damaged', 'poor', 'SALA ECOGRAFIA', 'Marcado con N en la planilla (no funciona) REVISAR: Confirmar a qué fila corresponde la N.'),
        ('AF-0009', 'Impresora color blanco', 1, 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0010', 'Electrocardiógrafo marca ZONCARE color blanco', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'La planilla no tiene ítem 9'),
        ('AF-0011', 'Cable de electrocardiógrafo', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0012', 'Cable para sensores', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0013', 'Sensores pectorales de colores adulto', 6, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0014', 'Sensores de miembros de colores adulto', 4, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0015', 'Sensores pectorales color azul pediátricos', 6, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0016', 'Sensores de miembros color azul pediátricos', 4, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0017', 'Doppler fetal color rosado', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0018', 'Monitor marca LG', 1, 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0019', 'Monitor marca MASTER G', 1, 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0020', 'Escritorio color café', 1, 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0021', 'Silla color naranja', 1, 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0022', 'Gradilla', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0023', 'Camilla ginecológica color café oscuro', 1, 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0024', 'Pierneras de camilla ginecológica', 2, 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0025', 'Camilla de revisión', 1, 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0026', 'Lámparas cuello de ganso', 2, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0027', 'Taburetes giratorios color café oscuro', 2, 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0028', 'Biombos color blanco', 2, 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0029', 'Porta suero', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0030', 'Mesa de mayo', 1, 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0031', 'Tambor de acero mediano', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0032', 'Ligadura color celeste', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0033', 'Balanza pediátrica color blanco', 1, 'medical_equipment', 'damaged', 'poor', 'SALA ECOGRAFIA', 'Marcada con N en la planilla (no funciona) REVISAR: Confirmar a qué fila corresponde la N.'),
        ('AF-0034', 'Bidón de agua celeste', 2, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0035', 'Botella porta gel grande', 2, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0036', 'Porta colposcopio de acero con dos brazos', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'La planilla no tiene ítem 36'),
        ('AF-0037', 'Cámara de colposcopio con tapa marca EDDAN', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0038', 'Cable de cámara', 1, 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0039', 'Laptop marca TOSHIBA', 1, 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0040', 'Cable de laptop color negro', 1, 'computer', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0041', 'Cables de colposcopio color negro', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0042', 'Porta pico', 4, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0043', 'Tela grande color celeste', 2, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0044', 'Tela grande color rosado', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0045', 'Tela para biombo color blanco', 1, 'furniture', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0046', 'Cauterizador', 2, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0047', 'Agujas de cauterizador', 42, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'Falta 1 respecto a planilla Planilla 43, entregado 42. REVISAR: Confirmar 42 vs 43.'),
        ('AF-0048', 'Regla de 60 cm', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0049', 'Negatoscopio', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', NULL),
        ('AF-0050', 'Caja de guantes', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Unidad: caja.'),
        ('AF-0051', 'Vaselina líquida', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Unidad: frasco.'),
        ('AF-0052', 'Otoscopio color blanco', 1, 'medical_equipment', 'active', 'good', 'SALA ECOGRAFIA', 'Fila sin numero en planilla'),
        ('AF-0053', 'Cubridores', 4, 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Fila sin numero en planilla'),
        ('AF-0054', 'Porta cubridor', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Fila sin numero en planilla'),
        ('AF-0055', 'Papel de electrocardiógrafo', 5, 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano Unidad: rollo.'),
        ('AF-0056', 'Taza de porcelana', 3, 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano'),
        ('AF-0057', 'Botella de alcohol en gel', 1, 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano Unidad: botella.'),
        ('AF-0058', 'Tabletas de carbón', 10, 'other', 'active', 'good', 'SALA ECOGRAFIA', 'Agregado a mano; cantidad corregida a 10 Unidad: tableta.'),
        ('AF-0059', 'Estante de fierro color café', 1, 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0060', 'Biombo blanco', 1, 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0061', 'Mesa de mayo color blanco, completa', 1, 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0062', 'Camilla de revisión color café', 1, 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0063', 'Silla de toma de presión color café', 1, 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0064', 'Extintor rojo', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'La planilla no tiene ítem 6'),
        ('AF-0065', 'Tambores de acero inoxidable', 4, 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0066', 'Botiquín de primeros auxilios', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0067', 'Charola de aluminio', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0068', 'Estetoscopio', 3, 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', 'Falta 1 respecto a planilla Planilla 4, entregado 3. REVISAR: Confirmar 3 vs 4.'),
        ('AF-0069', 'Tensiómetro (2 manuales y 2 digitales)', 4, 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0070', 'Vitrinas de aluminio color café plomo', 2, 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0071', 'Monitor de cámaras', 1, 'computer', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0072', 'Monitor de cámara grande', 1, 'computer', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0073', 'Bránulas de todo calibre', 72, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Diferencia importante frente a planilla Planilla 106, entregado 72.'),
        ('AF-0074', 'Equipo para enemas', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0075', 'Guantes estériles', 14, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Unidad: par. Planilla 19, entregado 14.'),
        ('AF-0076', 'Nebulizador celeste pequeño', 1, 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0077', 'Mascarillas', 4, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Cantidad corregida a mano en planilla'),
        ('AF-0078', 'Caja abierta de jeringas 3 ml', 12, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Entregado contado en piezas sueltas Planilla 1, entregado 12. REVISAR: Cantidad en pz vs caja.'),
        ('AF-0079', 'Caja abierta de agujas 21G 1 1/2', 8, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Entregado contado en piezas sueltas Planilla 2, entregado 8. REVISAR: Cantidad en pz vs caja.'),
        ('AF-0080', 'Caja abierta de agujas 27G 1 1/2', 137, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Entregado contado en piezas sueltas Planilla 2, entregado 137. REVISAR: Cantidad en pz vs caja.'),
        ('AF-0081', 'Oxímetro', 2, 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', 'Entregado mayor a planilla Planilla 1, entregado 2. REVISAR: Confirmar 2 vs 1.'),
        ('AF-0082', 'Micropore', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Diferencia frente a planilla Unidad: rollo. Planilla 7, entregado 1. REVISAR: Confirmar 1 vs 7.'),
        ('AF-0083', 'Nebulizador grande celeste', 1, 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0084', 'Balde de guantes abiertos', 2, 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0085', 'Vendas elásticas 20 cm', 4, 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0086', 'Sondas vesicales', 4, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Planilla 5, entregado 4.'),
        ('AF-0087', 'Termómetro de mercurio', 2, 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0088', 'Cinta métrica', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0089', 'Balanza con tallímetro', 1, 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0090', 'Taburete verde', 1, 'furniture', 'active', 'good', 'SALA ENFERMERIA', NULL),
        ('AF-0091', 'Hilos', 6, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0092', 'Balón de oxígeno grande', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0093', 'Porta suero', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0094', 'Gradilla', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0095', 'Caja abierta de jeringas 20 ml', 18, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0096', 'Caja abierta de jeringas 50 ml', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0097', 'Lidocaína', 5, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano Unidad: frasco.'),
        ('AF-0098', 'Matabicharaco color azul', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano REVISAR: Confirmar nombre del producto.'),
        ('AF-0099', 'Ácido acético', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano Unidad: frasco.'),
        ('AF-0100', 'Basureros', 3, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Agregado a mano'),
        ('AF-0101', 'Mortero', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie de la planilla'),
        ('AF-0102', 'Agujas de sutura', 6, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie REVISAR: Confirmar descripcion.'),
        ('AF-0103', 'Frascos de vidrio', 3, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0104', 'Bisturí', 7, 'medical_equipment', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0105', 'Tapón', 3, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0106', 'Vendas de yeso', 2, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0107', 'Solución glucosada', 2, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie Unidad: frasco.'),
        ('AF-0108', 'Riñonera plastica amarilla', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0109', 'Atomizador rosado', 1, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0110', 'Frascos de vidrio (segundo lote)', 7, 'other', 'active', 'good', 'SALA ENFERMERIA', 'Anexo manuscrito al pie'),
        ('AF-0111', 'Equipo de wifi', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0112', 'Frasco de vidrio con oxímetro verde', 2, 'medical_equipment', 'inactive', 'good', 'CONSULTORIO MEDICO 1', 'En planilla figura 1+1; sin dato en Entregado Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0113', 'Termómetro digital', 1, 'medical_equipment', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0114', 'Control', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', 'REVISAR: Precisar de qué equipo es el control.'),
        ('AF-0115', 'Engrampadora', 2, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0116', 'Perforadora', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0117', 'Candados grandes', 4, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0118', 'Candados pequeños', 2, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0119', 'Aspiradoras', 2, 'medical_equipment', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0120', 'Máscara grande color celeste', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0121', 'Máscara transparente', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0122', 'Lentes transparentes', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0123', 'Tóner', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0124', 'Cable plomo', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0125', 'Escritorio color café de dos piezas', 1, 'furniture', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0126', 'Impresora EPSON', 2, 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0127', 'Cable blanco y negro', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0128', 'Monitor', 2, 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0129', 'Cable negro de monitor', 1, 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0130', 'Teclado', 1, 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0131', 'Cable para teclado negro', 1, 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0132', 'Ratón con cable', 1, 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0133', 'Porta pico', 2, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', 'En planilla figura 1+1; numeración 21 repetida'),
        ('AF-0134', 'Basurero color negro', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Numeración 22 repetida en planilla'),
        ('AF-0135', 'Caldera eléctrica', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0136', 'Grampas, caja abierta', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Unidad: caja.'),
        ('AF-0137', 'Gestograma', 1, 'other', 'inactive', 'good', 'CONSULTORIO MEDICO 1', 'Entregado marcado con guion Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Confirmar si no fue entregado.'),
        ('AF-0138', 'Yurex', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0139', 'Porta lápiz de madera', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0140', 'Sillas cafés', 1, 'furniture', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0141', 'Sillón blanco con café', 2, 'furniture', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0142', 'Florero con flores', 1, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0143', 'Cámara', 1, 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Agregado a mano'),
        ('AF-0144', 'Flash', 1, 'computer', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Agregado a mano'),
        ('AF-0145', 'Glucómetro', 1, 'medical_equipment', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Agregado a mano'),
        ('AF-0146', 'Recetarios', 25, 'other', 'active', 'good', 'CONSULTORIO MEDICO 1', 'Agregado a mano'),
        ('AF-0147', 'Basurero color negro', 1, 'other', 'active', 'good', 'BAÑO', NULL),
        ('AF-0148', 'Jarra pequeña color café', 1, 'other', 'active', 'good', 'BAÑO', NULL),
        ('AF-0149', 'Limpiador de baño rosado', 1, 'other', 'active', 'good', 'BAÑO', 'Agregado a mano'),
        ('AF-0150', 'Escobas', 2, 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0151', 'Goma', 1, 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0152', 'Basurero', 1, 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0153', 'Toalla', 1, 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0154', 'Sillón pequeño', 1, 'furniture', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0155', 'Lavandina', 1, 'other', 'active', 'good', 'LAVANDERIA', 'Unidad: botella. Planilla 3, entregado 1.'),
        ('AF-0156', 'Limpia piso', 1, 'other', 'active', 'good', 'LAVANDERIA', 'Unidad: botella. Planilla 3, entregado 1.'),
        ('AF-0157', 'Virutilla', 1, 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0158', 'Esponja', 1, 'other', 'active', 'good', 'LAVANDERIA', NULL),
        ('AF-0159', 'Cepillos', 2, 'other', 'active', 'good', 'LAVANDERIA', 'Agregado a mano'),
        ('AF-0160', 'Balde', 1, 'other', 'active', 'good', 'LAVANDERIA', 'Agregado a mano'),
        ('AF-0161', 'Pupinel color blanco', 1, 'medical_equipment', 'active', 'good', 'ESTERILIZACION', 'En planilla figura 1+1 (equipo + cable); se desglosa'),
        ('AF-0162', 'Cable de pupinel', 1, 'medical_equipment', 'active', 'good', 'ESTERILIZACION', 'Desglosado del 1+1 del ítem 1'),
        ('AF-0163', 'Centrifugadora', 1, 'medical_equipment', 'active', 'good', 'ESTERILIZACION', 'En planilla figura 1+1 (equipo + cable); se desglosa'),
        ('AF-0164', 'Cable de centrifugadora', 1, 'medical_equipment', 'active', 'good', 'ESTERILIZACION', 'Desglosado del 1+1 del ítem 2'),
        ('AF-0165', 'Mesa de mayo de dos cuerpos con bandeja pequeña', 1, 'furniture', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0166', 'Cable blanco', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0167', 'Basurero naranja', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0168', 'Riñonera de plástico amarillo', 1, 'other', 'inactive', 'good', 'ESTERILIZACION', 'Entregado marcado con guion Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Confirmar si no fue entregado.'),
        ('AF-0169', 'Caja de equipo grande de metal con tapa', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0170', 'Riñoneras', 3, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0171', 'Riñonera redonda', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0172', 'Caja de curación con tapa', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0173', 'Espéculo S', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0174', 'Pinza diente de ratón', 2, 'medical_equipment', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0175', 'Pinza anatómica', 2, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0176', 'Tijera mayo', 2, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0177', 'Pinza Kelly', 3, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0178', 'Porta aguja', 6, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0179', 'Mango de bisturí', 3, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0180', 'Pinza punta fina', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0181', 'Pinza para campos', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0182', 'Pinza aro', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0183', 'Cureta pequeña larga', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0184', 'Cureta ancha', 2, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0185', 'Corta uña', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0186', 'Equipo de retiro de uñero', 1, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0187', 'Tubos celestes Chulumani', 8, 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 10, entregado 8.'),
        ('AF-0188', 'Tubos celestes Irupana', 45, 'other', 'active', 'good', 'ESTERILIZACION', 'Entregado mayor a planilla Planilla 34, entregado 45. REVISAR: Confirmar 45 vs 34.'),
        ('AF-0189', 'Tubos rojos', 5, 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 6, entregado 5.'),
        ('AF-0190', 'Tubos morados', 7, 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 8, entregado 7.'),
        ('AF-0191', 'Tubos amarillos', 8, 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 10, entregado 8.'),
        ('AF-0192', 'Prueba de embarazo', 1, 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 4, entregado 1.'),
        ('AF-0193', 'Tubos Eppendorf', 2, 'other', 'active', 'good', 'ESTERILIZACION', NULL),
        ('AF-0194', 'Toalla roja', 15, 'other', 'active', 'good', 'ESTERILIZACION', 'Planilla 1, entregado 15. REVISAR: Cifra dudosa: revisar 15 vs 1.'),
        ('AF-0195', 'Tubo Sandra', 1, 'other', 'active', 'good', 'ESTERILIZACION', 'Agregado a mano REVISAR: Confirmar descripcion.'),
        ('AF-0196', 'Paquete de bolsas negras, abierto', 4, 'other', 'active', 'good', 'ESTERILIZACION', 'Agregado a mano Unidad: paquete.'),
        ('AF-0197', 'Esponja', 1, 'other', 'active', 'good', 'ESTERILIZACION', 'Agregado a mano'),
        ('AF-0198', 'Sillones', 5, 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0199', 'Mesa', 1, 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0200', 'Timbre', 1, 'other', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0201', 'Cámara', 1, 'computer', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0202', 'Sillones de madera', 2, 'furniture', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0203', 'Manguera azul', 1, 'other', 'inactive', 'good', 'SALA DE ESPERA', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0204', 'Garrafa', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0205', 'Mesa amarilla', 1, 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0206', 'Mesa verde', 1, 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0207', 'Manguera de garrafa', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0208', 'Catre de una plaza', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0209', 'Payasa (colchoneta)', 1, 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0210', 'Frazada guinda', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0211', 'Frazada ploma con banderita', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0212', 'Cubrecama amarilla', 1, 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0213', 'Almohada con protector', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0214', 'Sillón', 1, 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0215', 'Silla', 1, 'furniture', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0216', 'Platos planos de plástico', 2, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0217', 'Plato hondo de porcelana azul', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0218', 'Plato hondo de plástico', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0219', 'Termo pequeño', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0220', 'Azucarera de porcelana', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0221', 'Tazas de porcelana', 2, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0222', 'Copa de vidrio', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0223', 'Copa de plástico', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0224', 'Canasta pequeña verde', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0225', 'Cucharón', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0226', 'Espumadera de metal', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0227', 'Cuchara de metal', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0228', 'Tenedor', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0229', 'Cuchillo de mesa', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0230', 'Cuchillo grande rojo', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0231', 'Raspador plano', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0232', 'Exprimidor plano', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0233', 'Olla mediana', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0234', 'Sartén grande', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.'),
        ('AF-0235', 'Jarra pequeña', 1, 'other', 'inactive', 'good', 'CUARTO', 'Columna Entregado en blanco Figura en la planilla pero sin entrega registrada — confirmar en el conteo físico. REVISAR: Falta registrar entregado.')
      ) AS v(tag, nombre, cantidad, tipo, estado, condicion, ambiente, notas)
      CROSS JOIN (SELECT "id" FROM "clinics" WHERE "name" ILIKE 'San Bartolom%' LIMIT 1) c
      ON CONFLICT ("assetTag") DO NOTHING
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM "assets" WHERE "assetTag" LIKE 'AF-%'`);
  }
}
