import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Carga el inventario de activos fijos de San Bartolomé desde la planilla del
 * traspaso: 207 filas y 500 unidades repartidas en 8 ambientes.
 *
 * Quedan **290 fichas**, por el criterio acordado con el usuario: hasta 5
 * unidades se abre una ficha por unidad —dos ecógrafos o tres estetoscopios se
 * siguen por separado, y uno se puede dar de baja sin tocar el otro—; por
 * encima de 5 va una sola ficha con la cantidad anotada, porque 72 bránulas o
 * 42 agujas de cauterizador no son activos que se sigan uno a uno.
 *
 * **Sin fecha ni precio de compra**: la planilla no los trae. La fecha se deja
 * en NULL (ver `MakeAssetPurchaseDateOptional`) y el precio en 0, con método
 * "sin depreciación". Poner la fecha de hoy habría hecho que dentro de cinco
 * años el sistema afirmara que un ecógrafo de segunda mano tiene cinco años.
 *
 * Las 40 fichas de material fungible (guantes, agujas, bránulas, tubos)
 * entran marcadas en sus notas: están en la planilla del traspaso y el acta
 * debe coincidir con ella, pero no son activos fijos y conviene poder
 * separarlas después.
 *
 * **La condición se carga como "buena" para todos**, que es una suposición: la
 * planilla no la registra. Es editable ficha por ficha.
 *
 * Idempotente por el índice único de `assetTag`.
 */
export class SeedSanBartolomeAssets1786340000000 implements MigrationInterface {
  name = 'SeedSanBartolomeAssets1786340000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Los importes van explícitos porque un INSERT de migración no dispara el
    // hook `@BeforeInsert` que normalmente los calcula, y son NOT NULL.
    await queryRunner.query(`
      INSERT INTO "assets"
        ("assetTag", "name", "type", "status", "condition", "purchasePrice", "purchaseDate",
         "depreciationMethod", "usefulLifeYears", "salvageValue", "currentValue",
         "accumulatedDepreciation", "monthlyDepreciation", "maintenanceIntervalMonths",
         "totalMaintenanceCost", "location", "notes", "isActive", "clinic_id")
      SELECT v.tag, v.nombre, v.tipo::"assets_type_enum", 'active', 'good', 0, NULL,
             'no_depreciation', 0, 0, 0, 0, 0, 0, 0, v.ambiente, v.notas, true, c."id"
      FROM (VALUES
        ('AF-0001', 'Ecógrafo color blanco marca CHAIZON más cable negro (1 de 2)', 'medical_equipment', 'SALA ECOGRAFIA', 'Registrado como 1+1 (equipo + cable)'),
        ('AF-0002', 'Ecógrafo color blanco marca CHAIZON más cable negro (2 de 2)', 'medical_equipment', 'SALA ECOGRAFIA', 'Registrado como 1+1 (equipo + cable)'),
        ('AF-0003', 'Escritorio porta ecógrafo color café de tres peldaños', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0004', 'Transductor intravaginal', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0005', 'Transductor convexo', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0006', 'Cables de transductores (1 de 2)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0007', 'Cables de transductores (2 de 2)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0008', 'Estabilizador de electricidad', 'computer', 'SALA ECOGRAFIA', NULL),
        ('AF-0009', 'Cable negro de estabilizador (1 de 2)', 'computer', 'SALA ECOGRAFIA', NULL),
        ('AF-0010', 'Cable negro de estabilizador (2 de 2)', 'computer', 'SALA ECOGRAFIA', NULL),
        ('AF-0011', 'Impresora color blanco', 'computer', 'SALA ECOGRAFIA', NULL),
        ('AF-0012', 'Electrocardiógrafo marca ZONCARE de color blanco', 'medical_equipment', 'SALA ECOGRAFIA', 'El original salta del 8 al 10'),
        ('AF-0013', 'Cable de electrocardiógrafo', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0014', 'Cable para sensores', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0015', 'Sensores pectorales de colores adulto', 'medical_equipment', 'SALA ECOGRAFIA', '6 unidades en una sola ficha.'),
        ('AF-0016', 'Sensores de miembros de colores adulto (1 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0017', 'Sensores de miembros de colores adulto (2 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0018', 'Sensores de miembros de colores adulto (3 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0019', 'Sensores de miembros de colores adulto (4 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0020', 'Sensores pectorales color azul pediátricos', 'medical_equipment', 'SALA ECOGRAFIA', '6 unidades en una sola ficha.'),
        ('AF-0021', 'Sensores de miembros color azul pediátricos (1 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0022', 'Sensores de miembros color azul pediátricos (2 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0023', 'Sensores de miembros color azul pediátricos (3 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0024', 'Sensores de miembros color azul pediátricos (4 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0025', 'Doppler fetal color rosado', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0026', 'Monitor marca LG', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0027', 'Monitor marca MASTER G', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0028', 'Escritorio color café', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0029', 'Silla color naranja', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0030', 'Gradilla', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0031', 'Camilla ginecológica color café oscuro', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0032', 'Pierneras de camilla ginecológica (1 de 2)', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0033', 'Pierneras de camilla ginecológica (2 de 2)', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0034', 'Camilla de revisión', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0035', 'Lámparas cuello de ganso (1 de 2)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0036', 'Lámparas cuello de ganso (2 de 2)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0037', 'Taburetes giratorios color café oscuro (1 de 2)', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0038', 'Taburetes giratorios color café oscuro (2 de 2)', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0039', 'Biombos color blanco (1 de 2)', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0040', 'Biombos color blanco (2 de 2)', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0041', 'Porta suero', 'other', 'SALA ECOGRAFIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0042', 'Mesa de mayo', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0043', 'Tambor de acero mediano', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0044', 'Ligadura color celeste', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0045', 'Balanza pediátrica color blanco', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0046', 'Bidón de agua celeste (1 de 2)', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0047', 'Bidón de agua celeste (2 de 2)', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0048', 'Botella porta gel grande (1 de 2)', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0049', 'Botella porta gel grande (2 de 2)', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0050', 'Porta colposcopio de acero con dos brazos', 'medical_equipment', 'SALA ECOGRAFIA', 'El original salta del 35 al 37'),
        ('AF-0051', 'Cámara de colposcopio con tapa marca EDDAN', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0052', 'Cable de cámara', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0053', 'Laptop marca TOSHIBA', 'computer', 'SALA ECOGRAFIA', NULL),
        ('AF-0054', 'Cable de laptop color negro', 'computer', 'SALA ECOGRAFIA', NULL),
        ('AF-0055', 'Cables de colposcopio color negro (1 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0056', 'Cables de colposcopio color negro (2 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0057', 'Cables de colposcopio color negro (3 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0058', 'Cables de colposcopio color negro (4 de 4)', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0059', 'Porta pico (1 de 2)', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0060', 'Porta pico (2 de 2)', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0061', 'Tela grande color celeste', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0062', 'Tela grande color rosado', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0063', 'Tela para biombo (1 de 2)', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0064', 'Tela para biombo (2 de 2)', 'furniture', 'SALA ECOGRAFIA', NULL),
        ('AF-0065', 'Cauterizador', 'medical_equipment', 'SALA ECOGRAFIA', NULL),
        ('AF-0066', 'Agujas de cauterizador', 'medical_equipment', 'SALA ECOGRAFIA', 'Cifra impresa tachada y corregida a mano a 42 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso. | 42 unidades en una sola ficha.'),
        ('AF-0067', 'Regla de 60 cm', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0068', 'Negatoscopio', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0069', 'Caja de guantes', 'other', 'SALA ECOGRAFIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0070', 'Vaselina líquida', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0071', 'Agua oxigenada (1 de 2)', 'other', 'SALA ECOGRAFIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0072', 'Agua oxigenada (2 de 2)', 'other', 'SALA ECOGRAFIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0073', 'Povidona', 'other', 'SALA ECOGRAFIA', NULL),
        ('AF-0074', 'Otoscopio blanco con cámara', 'furniture', 'SALA ECOGRAFIA', 'Ítem agregado a mano'),
        ('AF-0075', 'Cobridores (1 de 4)', 'other', 'SALA ECOGRAFIA', 'Ítem agregado a mano'),
        ('AF-0076', 'Cobridores (2 de 4)', 'other', 'SALA ECOGRAFIA', 'Ítem agregado a mano'),
        ('AF-0077', 'Cobridores (3 de 4)', 'other', 'SALA ECOGRAFIA', 'Ítem agregado a mano'),
        ('AF-0078', 'Cobridores (4 de 4)', 'other', 'SALA ECOGRAFIA', 'Ítem agregado a mano'),
        ('AF-0079', 'Porta cobridor', 'other', 'SALA ECOGRAFIA', 'Ítem agregado a mano'),
        ('AF-0080', 'Estante de fierro color café', 'furniture', 'SALA ENFERMERIA', NULL),
        ('AF-0081', 'Biombo banco', 'furniture', 'SALA ENFERMERIA', NULL),
        ('AF-0082', 'Mesa de mayo color blanco completo', 'furniture', 'SALA ENFERMERIA', NULL),
        ('AF-0083', 'Camilla de revisión color café', 'furniture', 'SALA ENFERMERIA', NULL),
        ('AF-0084', 'Silla de toma de presión café', 'furniture', 'SALA ENFERMERIA', NULL),
        ('AF-0085', 'Extintor rojo', 'other', 'SALA ENFERMERIA', 'El original salta del 5 al 7'),
        ('AF-0086', 'Tambores de acero inoxidable (1 de 4)', 'other', 'SALA ENFERMERIA', NULL),
        ('AF-0087', 'Tambores de acero inoxidable (2 de 4)', 'other', 'SALA ENFERMERIA', NULL),
        ('AF-0088', 'Tambores de acero inoxidable (3 de 4)', 'other', 'SALA ENFERMERIA', NULL),
        ('AF-0089', 'Tambores de acero inoxidable (4 de 4)', 'other', 'SALA ENFERMERIA', NULL),
        ('AF-0090', 'Botiquín de primeros auxilios', 'other', 'SALA ENFERMERIA', NULL),
        ('AF-0091', 'Charola de aluminio', 'other', 'SALA ENFERMERIA', NULL),
        ('AF-0092', 'Estetoscopio (1 de 3)', 'medical_equipment', 'SALA ENFERMERIA', 'Cantidad anotada a mano (x3)'),
        ('AF-0093', 'Estetoscopio (2 de 3)', 'medical_equipment', 'SALA ENFERMERIA', 'Cantidad anotada a mano (x3)'),
        ('AF-0094', 'Estetoscopio (3 de 3)', 'medical_equipment', 'SALA ENFERMERIA', 'Cantidad anotada a mano (x3)'),
        ('AF-0095', 'Tensiómetro (2 manuales y 2 digitales) (1 de 4)', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0096', 'Tensiómetro (2 manuales y 2 digitales) (2 de 4)', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0097', 'Tensiómetro (2 manuales y 2 digitales) (3 de 4)', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0098', 'Tensiómetro (2 manuales y 2 digitales) (4 de 4)', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0099', 'Vitrinas de aluminio café plomo (1 de 2)', 'furniture', 'SALA ENFERMERIA', NULL),
        ('AF-0100', 'Vitrinas de aluminio café plomo (2 de 2)', 'furniture', 'SALA ENFERMERIA', NULL),
        ('AF-0101', 'Monitor de cámaras', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0102', 'Monitor de cámara grande', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0103', 'Bránulas de todo calibre', 'other', 'SALA ENFERMERIA', 'Corregido a mano de 106 a 72 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso. | 72 unidades en una sola ficha.'),
        ('AF-0104', 'Equipo para enemas', 'other', 'SALA ENFERMERIA', NULL),
        ('AF-0105', 'Guantes estériles', 'other', 'SALA ENFERMERIA', 'Corregido a mano de 16 a 14 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso. | 14 unidades en una sola ficha.'),
        ('AF-0106', 'Nebulizador celeste pequeño', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0107', 'Mascarillas (1 de 4)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0108', 'Mascarillas (2 de 4)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0109', 'Mascarillas (3 de 4)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0110', 'Mascarillas (4 de 4)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0111', 'Equipo de mascarillas (1 de 3)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0112', 'Equipo de mascarillas (2 de 3)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0113', 'Equipo de mascarillas (3 de 3)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0114', 'Caja abierta de jeringas 3 ml', 'other', 'SALA ENFERMERIA', 'Anotado a mano como 1/2 caja | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso. | La planilla anota "0.5" (fracción).'),
        ('AF-0115', 'Caja abierta de agujas 23 G 1 1/2', 'other', 'SALA ENFERMERIA', 'Corregido a mano a 0 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0116', 'Caja abierta de agujas 21 G 1 1/2', 'other', 'SALA ENFERMERIA', 'Corregido a mano a 0 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0117', 'Caja abierta de agujas 27 G 1/2 (1 de 2)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0118', 'Caja abierta de agujas 27 G 1/2 (2 de 2)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0119', 'Oxímetro', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0120', 'Micropore', 'other', 'SALA ENFERMERIA', 'Corregido a mano a 1'),
        ('AF-0121', 'Nebulizador grande celeste', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0122', 'Balde de guantes abiertos (1 de 2)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0123', 'Balde de guantes abiertos (2 de 2)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0124', 'Vendas elásticas de 20 cm (1 de 4)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0125', 'Vendas elásticas de 20 cm (2 de 4)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0126', 'Vendas elásticas de 20 cm (3 de 4)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0127', 'Vendas elásticas de 20 cm (4 de 4)', 'other', 'SALA ENFERMERIA', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0128', 'Sondas vesicales (1 de 4)', 'other', 'SALA ENFERMERIA', 'Corregido a mano a 4 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0129', 'Sondas vesicales (2 de 4)', 'other', 'SALA ENFERMERIA', 'Corregido a mano a 4 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0130', 'Sondas vesicales (3 de 4)', 'other', 'SALA ENFERMERIA', 'Corregido a mano a 4 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0131', 'Sondas vesicales (4 de 4)', 'other', 'SALA ENFERMERIA', 'Corregido a mano a 4 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0132', 'Termómetro de mercurio (1 de 2)', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0133', 'Termómetro de mercurio (2 de 2)', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0134', 'Cinta métrica', 'other', 'SALA ENFERMERIA', NULL),
        ('AF-0135', 'Balanza con tallímetro', 'medical_equipment', 'SALA ENFERMERIA', NULL),
        ('AF-0136', 'Taburete verde', 'furniture', 'SALA ENFERMERIA', NULL),
        ('AF-0137', 'Equipo de wifi', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0138', 'Frasco de vidrio con oxímetro verde (1 de 2)', 'medical_equipment', 'CONSULTORIO MEDICO 1', 'Registrado como 1+1'),
        ('AF-0139', 'Frasco de vidrio con oxímetro verde (2 de 2)', 'medical_equipment', 'CONSULTORIO MEDICO 1', 'Registrado como 1+1'),
        ('AF-0140', 'Termómetro digital', 'medical_equipment', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0141', 'Control', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0142', 'Engrampadora (1 de 2)', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0143', 'Engrampadora (2 de 2)', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0144', 'Perforadora', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0145', 'Candados grandes (1 de 4)', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0146', 'Candados grandes (2 de 4)', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0147', 'Candados grandes (3 de 4)', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0148', 'Candados grandes (4 de 4)', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0149', 'Candados pequeños (1 de 2)', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0150', 'Candados pequeños (2 de 2)', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0151', 'Aspiradoras (1 de 2)', 'medical_equipment', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0152', 'Aspiradoras (2 de 2)', 'medical_equipment', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0153', 'Máscara grande color celeste', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0154', 'Máscara transparente', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0155', 'Lentes transparentes', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0156', 'Tóner', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0157', 'Cable plomo', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0158', 'Escritorio color café de dos piezas (1 de 2)', 'furniture', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0159', 'Escritorio color café de dos piezas (2 de 2)', 'furniture', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0160', 'Impresora EPSON', 'computer', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0161', 'Cable blanco y negro (1 de 2)', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0162', 'Cable blanco y negro (2 de 2)', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0163', 'Monitor', 'medical_equipment', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0164', 'Cable negro de monitor', 'medical_equipment', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0165', 'Teclado', 'computer', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0166', 'Cable para teclado negro', 'computer', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0167', 'Ratón + cable (1 de 2)', 'computer', 'CONSULTORIO MEDICO 1', 'El original repite la numeración 21 y 22'),
        ('AF-0168', 'Ratón + cable (2 de 2)', 'computer', 'CONSULTORIO MEDICO 1', 'El original repite la numeración 21 y 22'),
        ('AF-0169', 'Porta pico', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0170', 'Basurero color negro', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0171', 'Caldera eléctrica', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0172', 'Grampas abiertas', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0173', 'Gestograma', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0174', 'Yurex', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0175', 'Porta lápiz de madera', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0176', 'Sillas cafés (1 de 2)', 'furniture', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0177', 'Sillas cafés (2 de 2)', 'furniture', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0178', 'Sillón blanco con café', 'furniture', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0179', 'Florero con flores', 'other', 'CONSULTORIO MEDICO 1', NULL),
        ('AF-0180', 'Flash memory', 'other', 'CONSULTORIO MEDICO 1', 'Ítem agregado a mano'),
        ('AF-0181', 'Basurero color negro', 'other', 'BAÑO', NULL),
        ('AF-0182', 'Jarra pequeña café', 'other', 'BAÑO', NULL),
        ('AF-0183', 'Escobas (1 de 2)', 'other', 'LAVANDERIA', NULL),
        ('AF-0184', 'Escobas (2 de 2)', 'other', 'LAVANDERIA', NULL),
        ('AF-0185', 'Goma', 'other', 'LAVANDERIA', NULL),
        ('AF-0186', 'Basurero', 'other', 'LAVANDERIA', NULL),
        ('AF-0187', 'Toalla', 'other', 'LAVANDERIA', NULL),
        ('AF-0188', 'Sillón pequeño', 'furniture', 'LAVANDERIA', NULL),
        ('AF-0189', 'Lavandina', 'other', 'LAVANDERIA', 'Corregido a mano a 1'),
        ('AF-0190', 'Limpia piso', 'other', 'LAVANDERIA', 'Corregido a mano a 1'),
        ('AF-0191', 'Ace (detergente)', 'other', 'LAVANDERIA', 'Corregido a mano a 0'),
        ('AF-0192', 'Jaboncillo', 'other', 'LAVANDERIA', NULL),
        ('AF-0193', 'Virutilla', 'other', 'LAVANDERIA', NULL),
        ('AF-0194', 'Esponja', 'other', 'LAVANDERIA', NULL),
        ('AF-0195', 'Pupinel blanco más cable (1 de 2)', 'medical_equipment', 'ESTERILIZACION', 'Registrado como 1+1'),
        ('AF-0196', 'Pupinel blanco más cable (2 de 2)', 'medical_equipment', 'ESTERILIZACION', 'Registrado como 1+1'),
        ('AF-0197', 'Centrifugadora más cable (1 de 2)', 'medical_equipment', 'ESTERILIZACION', 'Registrado como 1+1'),
        ('AF-0198', 'Centrifugadora más cable (2 de 2)', 'medical_equipment', 'ESTERILIZACION', 'Registrado como 1+1'),
        ('AF-0199', 'Mesa de mayo de dos cuerpos con bandeja pequeña', 'furniture', 'ESTERILIZACION', NULL),
        ('AF-0200', 'Cable blanco', 'other', 'ESTERILIZACION', NULL),
        ('AF-0201', 'Basurero naranja', 'other', 'ESTERILIZACION', NULL),
        ('AF-0202', 'Riñonera de plástico amarillo', 'other', 'ESTERILIZACION', NULL),
        ('AF-0203', 'Caja de equipo grande de metal más su tapa', 'other', 'ESTERILIZACION', NULL),
        ('AF-0204', 'Riñoneras (1 de 3)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0205', 'Riñoneras (2 de 3)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0206', 'Riñoneras (3 de 3)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0207', 'Riñonera redonda', 'other', 'ESTERILIZACION', NULL),
        ('AF-0208', 'Caja de curación más tapa', 'other', 'ESTERILIZACION', NULL),
        ('AF-0209', 'Espéculo L', 'other', 'ESTERILIZACION', NULL),
        ('AF-0210', 'Espéculo S', 'other', 'ESTERILIZACION', NULL),
        ('AF-0211', 'Pinza diente de ratón (1 de 2)', 'computer', 'ESTERILIZACION', NULL),
        ('AF-0212', 'Pinza diente de ratón (2 de 2)', 'computer', 'ESTERILIZACION', NULL),
        ('AF-0213', 'Pinza anatómica (1 de 2)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0214', 'Pinza anatómica (2 de 2)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0215', 'Tijera mayo (1 de 2)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0216', 'Tijera mayo (2 de 2)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0217', 'Pinza Kelly (1 de 3)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0218', 'Pinza Kelly (2 de 3)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0219', 'Pinza Kelly (3 de 3)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0220', 'Porta aguja', 'other', 'ESTERILIZACION', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso. | 6 unidades en una sola ficha.'),
        ('AF-0221', 'Mango de bisturí (1 de 3)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0222', 'Mango de bisturí (2 de 3)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0223', 'Mango de bisturí (3 de 3)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0224', 'Pinza punta fina', 'other', 'ESTERILIZACION', NULL),
        ('AF-0225', 'Pinza para campos', 'other', 'ESTERILIZACION', NULL),
        ('AF-0226', 'Pinza aro', 'other', 'ESTERILIZACION', NULL),
        ('AF-0227', 'Cureta pequeña larga', 'other', 'ESTERILIZACION', NULL),
        ('AF-0228', 'Cureta ancha (1 de 2)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0229', 'Cureta ancha (2 de 2)', 'other', 'ESTERILIZACION', NULL),
        ('AF-0230', 'Corta uña', 'other', 'ESTERILIZACION', NULL),
        ('AF-0231', 'Equipo de retiro de uñero', 'other', 'ESTERILIZACION', '10 unidades en una sola ficha.'),
        ('AF-0232', 'Tubos celestes Chulumani', 'other', 'ESTERILIZACION', 'Anotado 34 + 17 con resultado manuscrito 45 (la suma daría 51) — VERIFICAR | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso. | 45 unidades en una sola ficha.'),
        ('AF-0233', 'Tubos celestes Irupana (1 de 5)', 'other', 'ESTERILIZACION', 'Corregido a mano a 5 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0234', 'Tubos celestes Irupana (2 de 5)', 'other', 'ESTERILIZACION', 'Corregido a mano a 5 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0235', 'Tubos celestes Irupana (3 de 5)', 'other', 'ESTERILIZACION', 'Corregido a mano a 5 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0236', 'Tubos celestes Irupana (4 de 5)', 'other', 'ESTERILIZACION', 'Corregido a mano a 5 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0237', 'Tubos celestes Irupana (5 de 5)', 'other', 'ESTERILIZACION', 'Corregido a mano a 5 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0238', 'Tubos rojos', 'other', 'ESTERILIZACION', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso. | 8 unidades en una sola ficha.'),
        ('AF-0239', 'Tubos morados', 'other', 'ESTERILIZACION', 'Material fungible: figura en el inventario de activos por estar en la planilla de traspaso. | 10 unidades en una sola ficha.'),
        ('AF-0240', 'Tubos amarillos', 'other', 'ESTERILIZACION', 'Corregido a mano a 1 | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso.'),
        ('AF-0241', 'Prueba de embarazo', 'other', 'ESTERILIZACION', 'Corregido a mano a 0'),
        ('AF-0242', 'Espéculos medianos (1 de 2)', 'other', 'ESTERILIZACION', 'Ítem agregado a mano'),
        ('AF-0243', 'Espéculos medianos (2 de 2)', 'other', 'ESTERILIZACION', 'Ítem agregado a mano'),
        ('AF-0244', 'Eppendorf (tubos)', 'other', 'ESTERILIZACION', 'Ítem agregado a mano | Material fungible: figura en el inventario de activos por estar en la planilla de traspaso. | 7 unidades en una sola ficha.'),
        ('AF-0245', 'Toalla pequeña roja', 'other', 'ESTERILIZACION', 'Ítem agregado a mano'),
        ('AF-0246', 'Sillones (1 de 5)', 'furniture', 'SALA DE ESPERA', NULL),
        ('AF-0247', 'Sillones (2 de 5)', 'furniture', 'SALA DE ESPERA', NULL),
        ('AF-0248', 'Sillones (3 de 5)', 'furniture', 'SALA DE ESPERA', NULL),
        ('AF-0249', 'Sillones (4 de 5)', 'furniture', 'SALA DE ESPERA', NULL),
        ('AF-0250', 'Sillones (5 de 5)', 'furniture', 'SALA DE ESPERA', NULL),
        ('AF-0251', 'Mesa', 'furniture', 'SALA DE ESPERA', NULL),
        ('AF-0252', 'Timbre', 'other', 'SALA DE ESPERA', NULL),
        ('AF-0253', 'Cámara', 'furniture', 'SALA DE ESPERA', NULL),
        ('AF-0254', 'Sillones de madera (1 de 2)', 'furniture', 'SALA DE ESPERA', NULL),
        ('AF-0255', 'Sillones de madera (2 de 2)', 'furniture', 'SALA DE ESPERA', NULL),
        ('AF-0256', 'Manguera azul', 'other', 'SALA DE ESPERA', NULL),
        ('AF-0257', 'Garrafa', 'other', 'CUARTO', NULL),
        ('AF-0258', 'Mesa amarilla', 'furniture', 'CUARTO', NULL),
        ('AF-0259', 'Mesa verde', 'furniture', 'CUARTO', NULL),
        ('AF-0260', 'Manguera de garrafa', 'other', 'CUARTO', NULL),
        ('AF-0261', 'Catre de una plaza', 'other', 'CUARTO', NULL),
        ('AF-0262', 'Payasa (colchón)', 'furniture', 'CUARTO', NULL),
        ('AF-0263', 'Frazada guinda', 'other', 'CUARTO', NULL),
        ('AF-0264', 'Frazada ploma con banderita', 'other', 'CUARTO', NULL),
        ('AF-0265', 'Cubrecama amarilla', 'furniture', 'CUARTO', NULL),
        ('AF-0266', 'Almohada con protector', 'other', 'CUARTO', NULL),
        ('AF-0267', 'Sillón', 'furniture', 'CUARTO', NULL),
        ('AF-0268', 'Silla', 'furniture', 'CUARTO', NULL),
        ('AF-0269', 'Platos de plástico planos (1 de 2)', 'other', 'CUARTO', NULL),
        ('AF-0270', 'Platos de plástico planos (2 de 2)', 'other', 'CUARTO', NULL),
        ('AF-0271', 'Plato hondo de porcelana azul', 'other', 'CUARTO', NULL),
        ('AF-0272', 'Plato hondo de plástico', 'other', 'CUARTO', NULL),
        ('AF-0273', 'Termo pequeño', 'other', 'CUARTO', NULL),
        ('AF-0274', 'Azucarera de porcelana', 'other', 'CUARTO', NULL),
        ('AF-0275', 'Tazas de porcelana (1 de 2)', 'other', 'CUARTO', NULL),
        ('AF-0276', 'Tazas de porcelana (2 de 2)', 'other', 'CUARTO', NULL),
        ('AF-0277', 'Copa de vidrio', 'other', 'CUARTO', NULL),
        ('AF-0278', 'Copa de plástico', 'other', 'CUARTO', NULL),
        ('AF-0279', 'Canasta pequeña verde', 'other', 'CUARTO', NULL),
        ('AF-0280', 'Cucharón', 'other', 'CUARTO', NULL),
        ('AF-0281', 'Espumadera de metal', 'other', 'CUARTO', NULL),
        ('AF-0282', 'Cuchara de metal', 'other', 'CUARTO', NULL),
        ('AF-0283', 'Tenedor', 'other', 'CUARTO', NULL),
        ('AF-0284', 'Cuchillo de mesa', 'furniture', 'CUARTO', NULL),
        ('AF-0285', 'Cuchillo grande rojo', 'other', 'CUARTO', NULL),
        ('AF-0286', 'Raspador plano', 'other', 'CUARTO', NULL),
        ('AF-0287', 'Exprimidor plano', 'other', 'CUARTO', NULL),
        ('AF-0288', 'Olla mediana', 'other', 'CUARTO', NULL),
        ('AF-0289', 'Sartén grande', 'other', 'CUARTO', NULL),
        ('AF-0290', 'Jarra pequeña', 'other', 'CUARTO', NULL)
      ) AS v(tag, nombre, tipo, ambiente, notas)
      CROSS JOIN (SELECT "id" FROM "clinics" WHERE "name" ILIKE 'San Bartolom%' LIMIT 1) c
      ON CONFLICT ("assetTag") DO NOTHING
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM "assets" WHERE "assetTag" LIKE 'AF-%'`);
  }
}
