import { Permission } from '../enums/permission.enum'
import { UserRoles } from '../enums/user-roles.enum'
import { MenuItem } from '../interfaces/menu-item.interface'

export const MENU_ITEMS: MenuItem[] = [
  {
    label: 'Dashboard Principal',
    icon: 'dashboard',
    route: '/dashboard/home',
    allowedRoles: [
      UserRoles.RECEPTIONIST,
      UserRoles.PHARMACIST,
      UserRoles.NURSE,
      UserRoles.DOCTOR,
      UserRoles.ADMIN,
      UserRoles.SUPER_ADMIN,
    ],
  },
  {
    label: 'Gestión del Consultorio Médico',
    icon: 'monitor_heart',
    route: '/medical', // Ruta padre, puede no usarse si todos los hijos tienen rutas
    allowedRoles: [
      UserRoles.RECEPTIONIST,
      UserRoles.NURSE,
      UserRoles.DOCTOR,
      UserRoles.PHARMACIST,
      UserRoles.ADMIN,
      UserRoles.SUPER_ADMIN,
    ],
    children: [
      {
        label: 'Pacientes',
        icon: 'people',
        route: '/dashboard/patients',
        allowedRoles: [
          UserRoles.RECEPTIONIST,
          UserRoles.NURSE,
          UserRoles.DOCTOR,
          UserRoles.ADMIN,
          UserRoles.SUPER_ADMIN,
        ],
        requiredPermissions: [Permission.PatientsRead],
      },
      {
        label: 'Expedientes Médicos',
        icon: 'description',
        route: '/dashboard/medical-records',
        allowedRoles: [UserRoles.DOCTOR, UserRoles.NURSE, UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.RecordsRead],
      },
      {
        label: 'Calendario de Citas',
        icon: 'calendar_today',
        route: '/dashboard/appointments',
        allowedRoles: [
          UserRoles.RECEPTIONIST,
          UserRoles.DOCTOR,
          UserRoles.NURSE,
          UserRoles.ADMIN,
          UserRoles.SUPER_ADMIN,
        ],
        requiredPermissions: [Permission.AppointmentsRead],
      },
      {
        label: 'Recetas Electrónicas',
        icon: 'receipt',
        route: '/dashboard/prescriptions',
        allowedRoles: [
          UserRoles.DOCTOR,
          UserRoles.PHARMACIST,
          UserRoles.ADMIN,
          UserRoles.SUPER_ADMIN,
        ],
        requiredPermissions: [Permission.PrescriptionsRead],
      },
      {
        label: 'Facturación y Pagos',
        icon: 'payment',
        route: '/dashboard/billing',
        allowedRoles: [UserRoles.RECEPTIONIST, UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.BillingRead],
      },
    ],
  },
  {
    label: 'Control de Farmacia',
    icon: 'medication',
    route: '/pharmacy',
    allowedRoles: [UserRoles.PHARMACIST, UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
    children: [
      {
        label: 'Inventario',
        icon: 'inventory',
        route: '/dashboard/pharmacy/inventory',
        allowedRoles: [UserRoles.PHARMACIST, UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.PharmacyInventoryManage],
      },
      {
        label: 'Generación de Pedidos',
        icon: 'shopping_cart',
        route: '/dashboard/pharmacy/order-generation',
        allowedRoles: [UserRoles.PHARMACIST, UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.PharmacyInventoryManage],
      },
      {
        label: 'Ventas y Dispensación',
        icon: 'point_of_sale',
        route: '/dashboard/pharmacy/sales-dispensing',
        allowedRoles: [UserRoles.PHARMACIST, UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.PharmacyDispense],
      },
      {
        label: 'Facturación',
        icon: 'receipt_long',
        route: '/dashboard/pharmacy/invoicing',
        allowedRoles: [UserRoles.PHARMACIST, UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.PharmacyBilling],
      },
    ],
  },
  {
    label: 'Reportes',
    icon: 'analytics',
    route: '/reports',
    allowedRoles: [UserRoles.DOCTOR, UserRoles.PHARMACIST, UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
    children: [
      {
        label: 'Informes Médicos',
        icon: 'medical_services',
        route: '/dashboard/reports/medical-reports',
        allowedRoles: [UserRoles.DOCTOR, UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.ReportsMedical],
      },
      {
        label: 'Reportes Financieros',
        icon: 'attach_money',
        route: '/dashboard/reports/financial-reports',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.ReportsFinancial],
      },
      {
        label: 'Control de Stock',
        icon: 'inventory_2',
        route: '/dashboard/reports/stock-control',
        allowedRoles: [UserRoles.PHARMACIST, UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.ReportsStock],
      },
    ],
  },
  {
    label: 'Control de Activos',
    icon: 'inventory',
    route: '/assets',
    allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
    children: [
      {
        label: 'Registro de Activos',
        icon: 'add_circle',
        route: '/dashboard/assets-control/registration',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.AssetsManage],
      },
      {
        label: 'Mantenimiento de Activos',
        icon: 'build',
        route: '/dashboard/assets-control/maintenance',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.AssetsManage],
      },
      {
        label: 'Control de Inventario de Activos',
        icon: 'inventory_2',
        route: '/dashboard/assets-control/inventory',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.AssetsManage],
      },
      {
        label: 'Reportes de Activos',
        icon: 'assessment',
        route: '/dashboard/assets-control/reports',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.AssetsManage],
      },
    ],
  },
  {
    label: 'Tareas Administrativas',
    icon: 'admin_panel_settings',
    route: '/admin',
    allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
    children: [
      {
        label: 'Gestión de Usuarios',
        icon: 'people_alt',
        route: '/dashboard/users',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.UsersManage],
      },
      {
        label: 'Lista de Usuarios',
        icon: 'group',
        route: '/dashboard/users/list',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.UsersManage],
      },
      {
        label: 'Agregar Usuario',
        icon: 'person_add',
        route: '/dashboard/users/register',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.UsersManage],
      },
      {
        label: 'Gestión de Roles',
        icon: 'security',
        route: '/dashboard/roles',
        allowedRoles: [UserRoles.SUPER_ADMIN], // Solo SUPER_ADMIN
        requiredPermissions: [Permission.RolesManage],
      },
      {
        label: 'Configuración del Sistema',
        icon: 'settings',
        route: '/dashboard/config',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.SettingsManage],
      },
      {
        label: 'Auditoría y Logs',
        icon: 'history',
        route: '/dashboard/audit',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.AuditRead],
      },
      {
        label: 'Respaldos y Restauración',
        icon: 'backup',
        route: '/dashboard/backup',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.BackupManage],
      },
      {
        label: 'Gestión de Clínicas',
        icon: 'domain',
        route: '/dashboard/clinics',
        allowedRoles: [UserRoles.SUPER_ADMIN], // Solo SUPER_ADMIN
        requiredPermissions: [Permission.ClinicsManage],
        children: [
          {
            label: 'Dashboard de Clínicas',
            icon: 'dashboard',
            route: '/dashboard/clinics',
            allowedRoles: [UserRoles.SUPER_ADMIN],
            requiredPermissions: [Permission.ClinicsManage],
          },
          {
            label: 'Lista de Clínicas',
            icon: 'list',
            route: '/dashboard/clinics/list',
            allowedRoles: [UserRoles.SUPER_ADMIN],
            requiredPermissions: [Permission.ClinicsManage],
          },
          {
            label: 'Nueva Clínica',
            icon: 'add_business',
            route: '/dashboard/clinics/new',
            allowedRoles: [UserRoles.SUPER_ADMIN],
            requiredPermissions: [Permission.ClinicsManage],
          },
        ],
      },
    ],
  },
  {
    label: 'Configuración Avanzada',
    icon: 'tune',
    route: '/advanced',
    allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
    children: [
      {
        label: 'Parámetros del Sistema',
        icon: 'settings_applications',
        route: '/dashboard/system-params',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.SettingsManage],
      },
      {
        label: 'Configuración de Notificaciones',
        icon: 'notifications',
        route: '/dashboard/notifications-config',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.SettingsManage],
      },
      {
        label: 'Plantillas de Documentos',
        icon: 'description',
        route: '/dashboard/document-templates',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.SettingsManage],
      },
      {
        label: 'Integración con APIs',
        icon: 'api',
        route: '/dashboard/api-integration',
        allowedRoles: [UserRoles.ADMIN, UserRoles.SUPER_ADMIN],
        requiredPermissions: [Permission.SettingsManage],
      },
    ],
  },
]
